Header Section
UmerZia/Portfolio pull request #1
Opened 2022-08-17 20:23 UTC by UmerZia

### Hi 👋, In this PR I:

- Designed mobile-first version.
- Added navigation and hero section.
- Install Linters.

2022-08-17 21:11 UTC, cynthiainga requested changes
Hi @UmerZia, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit history ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 21:11 UTC, cynthiainga commented on README.md
> +
- [ ] I think it would be nice to add explicit steps on how to clone and run your project locally, as this will be helpful to non-technical users. This includes git clone `URL`, cd `project_name`, etc. You can put the steps to clone and run the project in a new `Getting Started` section under the project's description 🙃 🙃

2022-08-17 21:11 UTC, cynthiainga commented on README.md
> +## Authors
- [ ] I think as you are the only `Author` in this project it's not necessary to write `Author` with `s`, please kindly delete the `s` 😁 😁

2022-08-17 21:11 UTC, cynthiainga commented on README.md
> +
- [ ] Please kindly add as well the `Acknowledgments` part just below the `Show your support` part to your README file 🙃 🙃

2022-08-17 21:49 UTC, UmerZia commented on README.md
> +## Authors
Thanks for mentioning the typo mistake! 😄 
Fixed it 👍

2022-08-17 21:49 UTC, UmerZia commented on README.md
> +
Done! 👍

2022-08-17 21:51 UTC, UmerZia commented on README.md
> +
Kindly mention the **optional changes** as I think this is more like a suggestion rather than a mistake 😄 
But I have done it!

2022-08-17 21:54 UTC, UmerZia commented on index.html
> +
I am a bit confused about your last point, Kindly may you explain how the **<nav>** tag improves the user experience for mobile devices, if you attach an article that will be a great help for me to learn more about **<nav>** tag. 💯

2022-08-17 22:38 UTC, UmerZia commented on index.html
> +
I mean the nav tag

2022-08-17 23:06 UTC, UmerZia commented
I have applied all the changes which were requested by the @cynthiainga 😄

2022-08-18 00:12 UTC, mavericks-db requested changes
Hi @UmerZia 😃 ,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

 ## Highlights
- Have used the right GitHub flow ✅
- Meaningful title and summary for PR ✅
- Professional README.md file ✅
- Linter checks passed ✅

 ## Required Changes ♻️

- [x] As highlighted by the previous code reviewer, you should implement the `nav` tag.
The `nav` tag is for semantics reasons and the right position of the icon is for convention and user experience for mobile devices. Please wrap the hamburger icon with the `nav` tag.

_Check the comments under the review._

## Optional suggestions

- **[OPTIONAL]** Please fix the `id` selector for your header. Based on your CSS stylesheet, it should be `nav` instead of `navbar`.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Code review by **Mavericks De Leon Balitaan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 00:22 UTC, UmerZia commented on index.html
> +<header class="container" id="navbar">
Sorry, my bad I submit the PR without watching the preview! 😄

2022-08-18 00:28 UTC, UmerZia commented
Done!

2022-08-18 00:29 UTC, UmerZia commented on index.html
> +    </div>
Done!

2022-08-18 00:50 UTC, ElsonOtake approved these changes
# status: APPROVED :green_circle: :100: 

Hi @UmerZia, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

![Minions](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. 👍 👍 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 00:54 UTC, merged